### ISSUE TITLE
Problem with array

### ISSUE THREAD

**Issue by Qwebeck** [Artinov/express-auth-Qwebeck#1]
Hello 
I have a problem with forEach function which must compare data from JSON.object with form values
It doesn't work 
Terminal show error that look so:
```
"TypeError: Cannot read property 'login' of undefined
    at D:\artinov\express-auth-Qwebeck\index.js:22:29
    at Array.forEach (native)
    at D:\artinov\express-auth-Qwebeck\index.js:21:7
    at Layer.handle [as handle_request] (D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\layer.js:95:5)
    at D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\index.js:335:12)
    at next (D:\artinov\express-auth-Qwebeck\node_modules\express\lib\router\index.js:275:10)"
```
But when i write code without forEach it works correct and show result of compare but only for first element of array
Maybe i wrote function incorrectly
I push my code where forEach is comment
Help please with this and say me where is my error
Thank you

**Comment by eko24ive** [comment]
Ok @Qwebeck I will take a look

**Comment by eko24ive** [comment]
So, it's comparing only first user - because you've explictly told it to do so:
```js
if(req.body.login===users[0].login && req.body.password===users[0].password){
```
Using `users[0]` will always compare first element of array, which means you're not iterating through array.

Using `.forEach()` loop is right desicion, but look:
```js
users.forEach(function(i,users){
```

In this case `i` variable will represent element of array, and `users` variable will represent index of element , while you refering to `users` thinking of it as user data object.
Let me know if this helps you

**Comment by Qwebeck** [comment]
No
I don't understand correct what i need to do 
I try to tall how i understand my target and how i try to perform it
I delete from function arguments argument users and i 
Than add argument e and try to see in console element with number [0]
But in terminal i saw message which say that it cannot read property of undefined
Also i delete all arguments from if function 
Now she look so
`if(req.body.login===users.login && req.body.password===users.password)`
After this server start working again but problem with array is  actual

**Comment by eko24ive** [comment]
Hi @Qwebeck have you tried to fix this issue like I showed it on video screencast ?

**Comment by Qwebeck** [comment]
Yes,all works
Thank you
